{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.zookeeper.port }}
      targetPort: client
      protocol: TCP
      name: client
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
{{- end }} 