replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "7.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 27017

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Configurações do MongoDB
mongodb:
  port: 27017
  database: devorbit
  username: admin
  password: devorbit123
  authEnabled: false # Desabilitado para desenvolvimento

# Persistência
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

# Configurações de segurança
security:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999
