replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Configurações do PostgreSQL
postgres:
  database: devorbit
  username: postgres
  password: devorbit123
  port: 5432

# Persistência
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

# Configurações de segurança
security:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999
