replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "7.0-alpine"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 6379

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Configurações do Redis
redis:
  port: 6379
  password: ""
  maxmemory: "256mb"
  maxmemoryPolicy: "allkeys-lru"

# Persistência
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
